//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.3074
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

using System;

	public class MonoTODOAttribute : Attribute
	{
		public MonoTODOAttribute ()
		{
		}

		public MonoTODOAttribute (string desc)
		{
		}
	}
